name: Fundamentals

on:
  push:
    branches: [main]
  fork:
    branches: [main]

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: '0'
    - name: Setup Python
      if: always()
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.10.6
    - name: Set up grading environment
      run: |
        sudo apt-get update
        sudo python -m pip install --upgrade pip
        sudo python -m pip install gatorgrade --ignore-installed PyYAML
    - name: Grade repository
      run: |
        gatorgrade --config gatorgrade.yml --report file json gatorgrade_summary.json
      if: always()
      env:
        PIPENV_VENV_IN_PROJECT: 1
        PIPENV_IGNORE_VIRTUALENVS: 1
